language: bash

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH

install:
  - cabal update && cabal install shellcheck
  - sudo sh -c "`curl -L https://raw.github.com/rylnd/shpec/master/install.sh`"

script: make